// utils/teaching.jsx
export function TeachingSection({ data }) {
  return (
    data && data.length > 0 && <section className="section research-contents">
        <h2 className="subtitle">
          teaching
        </h2>
        {
        data.map((teach, index) => {
          return (
            <div className="box" key={index}>
              <article className="media">
                <figure className="media-left has-text-right">
                  <p><strong>{ teach.period.start } - { teach.period.end }</strong></p>
                </figure>
                <div className="media-content">
                  <div className="content">
                    <p>
                    <a href={teach.course.link}>{ teach.course.name }</a>,&nbsp;
                    <a href={teach.degree.link}>{ teach.degree.name }</a>,&nbsp;
                    <a href={teach.university.link}>{ teach.university.name }</a>
                    </p>
                  </div>
                </div>
              </article>
            </div>
          )
        })
      }
    </section>
  )
}

// src/components/Teaching.vue
<template>
    <page-section section-title="teaching" section-slug="teaching">
      <div class="teaching">
        <div class="teaching-entry" v-for="entry in teaching" :key="entry.title">
          <div class="teaching-entry__year">
            {{ entry.period.start }} - {{ entry.period.end }}
          </div>
          <div class="teaching-entry__content">
            <a :href="entry.course.link">{{ entry.course.name }}</a>,
            <a :href="entry.degree.link">{{ entry.degree.name }}</a>,
            <a :href="entry.university.link">{{ entry.university.name }}</a>
          </div>
        </div>
      </div>
    </page-section>
</template>

<script>
import PageSection from './Section'
import teachingData from '../../data/teaching.json'

export default {
  components: {
    PageSection
  },
  data () {
    return {
      teaching: teachingData
    }
  }
}
</script>

<style>
.teaching {
  margin: 0 auto;
  width: 90%;
}
.teaching-entry {
  display: flex;
  margin: 20px 5px;
}
.teaching-entry__year {
  width: 140px;
  padding-right: 5px;
  font-weight: bold;
}
.teaching-entry__content {
  padding-left: 15px;
  text-align: justify;
}
</style>
