// src/components/Article.vue
<template>
  <div class="article">
    <span class="article-title">{{ this.researchArticle.title }}</span>{{ authors }}<span class="article-journal" v-html="journal"></span>{{ volumeAndPages }}{{ year }}.
    <span v-html="link"></span>
  </div>
</template>

<script>
export default {
  name: 'researchArticle',
  props: [ 'researchArticle' ],
  computed: {
    authors () {
      if (this.researchArticle.authors.length === 0) {
        return ''
      }

      let authorsString = ', with '
      if (this.researchArticle.authors.length === 1) {
        authorsString += this.researchArticle.authors[0]
      } else {
        authorsString +=
          this.researchArticle.authors.slice(0, -1).join(', ') +
          ' and ' +
          this.researchArticle.authors.slice(-1)
      }
      return authorsString
    },
    journal () {
      if (this.researchArticle.journal) {
        return `. <i>${this.researchArticle.journal}</i>`
      }
      return ''
    },
    volumeAndPages () {
      if (this.researchArticle.volume && this.researchArticle.pages) {
        return `. ${this.researchArticle.volume}, ${this.researchArticle.pages}`
      }
      return ''
    },
    year () {
      if (this.researchArticle.year) {
        return `. (${this.researchArticle.year})`
      }
      return ''
    },
    link () {
      if (this.researchArticle.link) {
        return `<a href="${this.researchArticle.link}">Link</a>.`
      }
      return ''
    }
  }
}
</script>

<style lang="scss">
.article {
  text-align: justify;
  margin-top: 25px;

  &-title {
    quotes: '"''"';

    &:before {
      content: open-quote;
    }
    &:after {
      content: close-quote;
    }
  }

  &-journal {
    font-style: italic;
  }
}
</style>

// utils/article.jsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faFileAlt } from '@fortawesome/free-solid-svg-icons'

export function Article({ article }) {
    const authors = () => {
        if (article.authors.length === 0) {
          return ''
        }
  
        let authorsString = ', with '
        if (article.authors.length === 1) {
          authorsString += article.authors[0]
        } else {
          authorsString +=
            article.authors.slice(0, -1).join(', ') +
            ' and ' +
            article.authors.slice(-1)
        }
        return authorsString
      }

    const journal = () => {
        if (article.journal) {
          return <>. <i>{ article.journal }</i></>
        }
      }

    const volumeAndPages = () => {
        if (article.volume && article.pages) {
          return `. ${article.volume}, ${article.pages}`
        }
      }

    const year = () => {
        if (article.year) {
          return `. (${article.year})`
        }
        return ''
      }

    const link = () => {
        if (article.link) {
          return <a href={article.link}><FontAwesomeIcon icon={faFileAlt}/></a>
        }
        return ''
      }

    return (
        <div className="article">
            <span className="article-title">"{ article.title }"</span>
            { authors() }
            <span className="article-journal">{ journal() }</span>
            { volumeAndPages() } 
            { year() }.&nbsp;
            { link() }
        </div>
    )
}


export function ArticleSection({ title, articles }) {
  return (
    articles && articles.length > 0 && <section className="section research-contents">
        <h2 className="subtitle">
          { title }
        </h2>
      {
        articles.map((article, index) => {
          return (
            <div className="box" key={index}>
              <article className="media">
                <div className="media-content">
                  <div className="content">
                    <Article article={article}/>
                  </div>
                </div>
              </article>
            </div>
          )
        })
      }
    </section>
  )
}
