// src/components/Education.vue
<template>
    <page-section section-title="education" section-slug="education">
      <div class="education">
        <div class="education-entry" v-for="entry in education" :key="entry.title">
          <div class="education-entry__year">
            {{ entry.year }}
          </div>
          <div class="education-entry__content">
            <a :href="entry.titulation.link">{{ entry.titulation.name }}</a>
            at <a :href="entry.university.link">{{ entry.university.name }}</a>
          </div>
        </div>
      </div>
    </page-section>
</template>

<script>
import PageSection from './Section'
import educationData from '../../data/education.json'

export default {
  components: {
    PageSection
  },
  data () {
    return {
      education: educationData
    }
  }
}
</script>

<style>
.education-entry {
  display: flex;
  margin: 20px 0;
}
.education-entry__year {
  width: 85px;
  padding-right: 20px;
  font-weight: bold;
  text-align: right;
}
.education-entry__content {
  width: 100%;
  text-align: justify;
}
</style>

// pages/education.jsx
import education from '../data/education.json'
import ReactMarkdown from 'react-markdown'

export default function Education() {
  return (
    <div className="">
      <section className="section education-header">
        <h1 className="title">
          education
        </h1>
      </section>

      <section className="section education-contents">
      {
        education.map((certification, index) => {
          return (
            <div className="box" key={index}>
              <article className="media">
                <figure className="media-left has-text-right">
                  <p><strong>{ certification.year }</strong></p>
                </figure>
                <div className="media-content">
                  <div className="content">
                    <p>
                      <span className="is-size-6">
                      <a href={ certification.titulation.link }>{ certification.titulation.name }</a>
                      &nbsp;at&nbsp;
                      <a href={ certification.university.link }>{ certification.university.name }</a>
                      </span>
                    </p>
                  </div>
                </div>
              </article>
            </div>
          )
        })
      }
      </section>
    </div>
  ) 
}
